/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/esqueci-senha'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/clientes'
    | '/dashboard'
    | '/kanban'
    | '/projetos'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/esqueci-senha'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/clientes'
    | '/dashboard'
    | '/kanban'
    | '/projetos'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/esqueci-senha'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/kanban'
    | '/_authenticated/projetos'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
